### PR TITLE
Fix minimum text holder height being based on hint text instead of actual text (#120)

### LINKED ISSUE #120: [BUG] [UI] Heading text block minimum height is computed using prompt text
In both view and edit note activities, the minimum height of heading text blocks is computed using the prompt text (in case of heading blocks *"Add Heading..."*) instead of using the actual content of the text block.
When using the Italian translation, where the prompt text spans on two lines, this problem brings the following UI inconsistency when the text is only one line long:
photo6033016213254286826
photo6033016213254286827
Opposed to what happens with English translation:
photo6033016213254286854

### PR DESCRIPTION
**Pull request by Fs00**
I've fixed #120 by removing useless hint texts for TextViews used in FormatTextViewHolder (since they're never displayed when their content is empty) and by removing the hint for the EditTexts programmatically when they are not empty anymore (obviously the hint is restored when the EditText becomes empty again).

### CODE REVIEW

File: base/src/main/java/com/maubis/scarlet/base/note/formats/recycler/FormatTextViewHolder.kt [hunk 1]
```diff
@@ -95,10 +97,21 @@ open class FormatTextViewHolder(context: Context, view: View) : FormatViewHolder
...
+
+    hideEditHintIfTextIsEmpty(s)
     format!!.text = s.toString()
     activity.setFormat(format!!)
   }
 
+  // Workaround to avoid this holder being higher than the text contained in it when hint text
+  // occupies more lines than the text inserted by the user
+  private fun hideEditHintIfTextIsEmpty(text: CharSequence) {
+    if (text.isEmpty())
```
Comment (BijoySingh) [inline base/src/main/java/com/maubis/scarlet/base/note/formats/recycler/FormatTextViewHolder.kt]:
```
edit.hint = when {
  text.isEmpty() -> editHint
  else -> ""
}
```

File: base/src/main/java/com/maubis/scarlet/base/note/formats/recycler/FormatTextViewHolder.kt [hunk 2]
```diff
@@ -95,10 +97,21 @@ open class FormatTextViewHolder(context: Context, view: View) : FormatViewHolder
...
     }
+
+    hideEditHintIfTextIsEmpty(s)
     format!!.text = s.toString()
     activity.setFormat(format!!)
   }
 
+  // Workaround to avoid this holder being higher than the text contained in it when hint text
+  // occupies more lines than the text inserted by the user
+  private fun hideEditHintIfTextIsEmpty(text: CharSequence) {
```
Comment (BijoySingh) [inline base/src/main/java/com/maubis/scarlet/base/note/formats/recycler/FormatTextViewHolder.kt]: `showHintWhenTextIsEmpty`

**Comment by Fs00** [comment]
Ok. The call to the method is already made in onTextChange method.
If I've understood correctly, I should now remove all references to hints included in XML layout files.
Do you prefer the method that retrieves the hint string being located in FormatType enum or in FormatTextViewHolder class?
I'll upload a screen capture of the working fix when I'll have made the adjustments you asked for.

**Comment by Fs00** [comment]
I've updated my commit as you asked and I've also improved the class to use a lateinit property for the format in order to avoid the use of `!!` operator (bad practice!).

File: base/src/main/java/com/maubis/scarlet/base/core/format/FormatType.kt [hunk 3]
```diff
@@ -13,5 +13,5 @@ enum class FormatType {
   CODE,
   QUOTE,
   SEPARATOR,
-  EMPTY,
+  EMPTY
```
Comment (BijoySingh) [inline base/src/main/java/com/maubis/scarlet/base/core/format/FormatType.kt]: Undo this maybe?  

Format should ideally be 1:1 to actual UI blocks. :)

File: base/src/main/java/com/maubis/scarlet/base/note/formats/recycler/FormatTextViewHolder.kt [hunk 4]
```diff
@@ -30,7 +30,7 @@ open class FormatTextViewHolder(context: Context, view: View) : FormatViewHolder
   protected val edit: EditText = root.findViewById(R.id.edit)
   protected val actionMove: ImageView = root.findViewById(R.id.action_move_icon)
 
-  protected var format: Format? = null
+  protected lateinit var format: Format
```
Comment (BijoySingh) [inline base/src/main/java/com/maubis/scarlet/base/note/formats/recycler/FormatTextViewHolder.kt]: Thanks!

Really hope this doesnt crash. I don't trust  recycler view lifecycles a lot. But #yolo

File: base/src/main/java/com/maubis/scarlet/base/core/format/FormatType.kt (hunk 3 above)
Comment (Fs00) [reply base/src/main/java/com/maubis/scarlet/base/core/format/FormatType.kt]: Hmm what's the problem here? I've just removed a trailing comma, the actual content hasn't changed.

File: base/src/main/java/com/maubis/scarlet/base/note/formats/recycler/FormatTextViewHolder.kt (hunk 4 above)
Comment (Fs00) [reply base/src/main/java/com/maubis/scarlet/base/note/formats/recycler/FormatTextViewHolder.kt]: It shouldn't cause any problem. The only difference is that now accessing format when it is uninitialized will throw a `UninitializedPropertyAccessException` instead of a `NullPointerException` (because you were using `!!` all the time).

**Comment by Fs00** [comment]
@BijoySingh I don't this needs any other changes before merging, check my comment on your review.

File: base/src/main/java/com/maubis/scarlet/base/core/format/FormatType.kt (hunk 3 above)
Comment (BijoySingh) [reply base/src/main/java/com/maubis/scarlet/base/core/format/FormatType.kt]: Oh sorry. That was a stupid comment.
